import enum


class Application(str, enum.Enum):
    SOCIAL = "SOCIAL"
    GMAIL = "GMAIL"
    FINANCE = "FINANCE"
    SECURITY_CENTER = "SECURITY_CENTER"


class ResourceSensitivity(str, enum.Enum):
    PUBLIC = "PUBLIC"
    INTERNAL = "INTERNAL"
    CONFIDENTIAL = "CONFIDENTIAL"
    RESTRICTED = "RESTRICTED"


class BehavioralState(str, enum.Enum):
    NORMAL = "NORMAL"
    DRIFT = "DRIFT"
    SUSPICIOUS = "SUSPICIOUS"
    HIGH_RISK = "HIGH_RISK"


class AlertSeverity(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AlertStatus(str, enum.Enum):
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    MARKED_BENIGN = "MARKED_BENIGN"
    MARKED_EXPECTED = "MARKED_EXPECTED"
    MARKED_SUSPICIOUS = "MARKED_SUSPICIOUS"
    CONFIRMED_INCIDENT = "CONFIRMED_INCIDENT"


class ContextType(str, enum.Enum):
    PROJECT_ASSIGNMENT = "PROJECT_ASSIGNMENT"
    ROLE_CHANGE = "ROLE_CHANGE"
    APPROVED_TRAVEL = "APPROVED_TRAVEL"
    NEW_DEVICE_APPROVAL = "NEW_DEVICE_APPROVAL"
    TEMPORARY_ACCESS = "TEMPORARY_ACCESS"
    MAINTENANCE_ACTIVITY = "MAINTENANCE_ACTIVITY"


class BaselineType(str, enum.Enum):
    LONG_TERM = "LONG_TERM"
    RECENT = "RECENT"


class ScenarioName(str, enum.Enum):
    NORMAL_ORGANIZATION = "NORMAL_ORGANIZATION"
    LEGITIMATE_PROJECT_CHANGE = "LEGITIMATE_PROJECT_CHANGE"
    COMPROMISED_ACCOUNT = "COMPROMISED_ACCOUNT"
    MALICIOUS_INSIDER = "MALICIOUS_INSIDER"
    CROSS_APPLICATION_ATTACK = "CROSS_APPLICATION_ATTACK"


class SimulationStatus(str, enum.Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
