/**
 * GENERATED by scripts/generate-population.mjs — do not edit by hand.
 * Committed deliberately: nothing randomises at runtime, so the numbers in the
 * demo video and the numbers a judge sees are the same numbers (PRD §6).
 */
import type { CompositeTimeline } from "./types";

/**
 * Composite timelines for the queue rows that are not one of the three authored
 * scenarios, so every row a judge clicks has a populated timeline lane set.
 * Built from one action template per dominant detector — see the generator.
 */
export const QUEUE_TIMELINES: CompositeTimeline[] = [
  {
    "subjectId": "subject_7741",
    "session": [
      {
        "t": 138,
        "ts": "2026-09-14T02:18:06Z",
        "action": "okta.session.start",
        "sensitivity": "low",
        "note": "Service credential · CI runner",
        "asnChange": true,
        "firstEver": true
      }
    ],
    "trajectory": [
      {
        "t": 144,
        "ts": "2026-09-14T02:24:48Z",
        "action": "aws.sts.assume_role",
        "resource": "ci-deploy-svc-legacy",
        "sensitivity": "critical",
        "note": "ci-deploy-svc-legacy · decoy credential"
      },
      {
        "t": 149,
        "ts": "2026-09-14T02:29:23Z",
        "action": "github.repo.clone",
        "resource": "ledger-api",
        "sensitivity": "critical",
        "note": "ledger-api · first ever",
        "firstEver": true
      },
      {
        "t": 157,
        "ts": "2026-09-14T02:37:19Z",
        "action": "jenkins.job.trigger",
        "resource": "deploy-ledger-api",
        "sensitivity": "high",
        "note": "deploy-ledger-api · outside change window"
      },
      {
        "t": 570,
        "ts": "2026-09-14T09:30:30Z",
        "action": "jira.issue.comment",
        "sensitivity": "low"
      },
      {
        "t": 676,
        "ts": "2026-09-14T11:16:52Z",
        "action": "slack.channel.message",
        "sensitivity": "low"
      },
      {
        "t": 790,
        "ts": "2026-09-14T13:10:10Z",
        "action": "confluence.page.view",
        "sensitivity": "low"
      },
      {
        "t": 905,
        "ts": "2026-09-14T15:05:35Z",
        "action": "jira.issue.transition",
        "sensitivity": "low"
      },
      {
        "t": 1012,
        "ts": "2026-09-14T16:52:04Z",
        "action": "github.pr.review",
        "sensitivity": "low"
      }
    ],
    "context": [],
    "risk": [
      {
        "t": 0,
        "risk": 17
      },
      {
        "t": 143,
        "risk": 17
      },
      {
        "t": 144,
        "risk": 43
      },
      {
        "t": 149,
        "risk": 70
      },
      {
        "t": 157,
        "risk": 96
      },
      {
        "t": 1439,
        "risk": 96
      }
    ]
  },
  {
    "subjectId": "subject_5530",
    "session": [
      {
        "t": 201,
        "ts": "2026-09-14T03:21:27Z",
        "action": "okta.session.start",
        "sensitivity": "medium",
        "note": "Corporate ASN · endpoint reported locked",
        "asnChange": true,
        "firstEver": true
      }
    ],
    "trajectory": [
      {
        "t": 208,
        "ts": "2026-09-14T03:28:16Z",
        "action": "aws.ssm.start_session",
        "resource": "bastion-01",
        "sensitivity": "high",
        "note": "bastion-01 · session manager"
      },
      {
        "t": 217,
        "ts": "2026-09-14T03:37:19Z",
        "action": "rds.snapshot.create",
        "resource": "payments-db",
        "sensitivity": "critical",
        "note": "payments-db · manual snapshot"
      },
      {
        "t": 225,
        "ts": "2026-09-14T03:45:15Z",
        "action": "aws.s3.put_object",
        "resource": "s3://ops-scratch-3311",
        "sensitivity": "critical",
        "note": "s3://ops-scratch-3311 · first ever",
        "firstEver": true
      },
      {
        "t": 570,
        "ts": "2026-09-14T09:30:30Z",
        "action": "jira.issue.comment",
        "sensitivity": "low"
      },
      {
        "t": 676,
        "ts": "2026-09-14T11:16:52Z",
        "action": "slack.channel.message",
        "sensitivity": "low"
      },
      {
        "t": 790,
        "ts": "2026-09-14T13:10:10Z",
        "action": "confluence.page.view",
        "sensitivity": "low"
      },
      {
        "t": 905,
        "ts": "2026-09-14T15:05:35Z",
        "action": "jira.issue.transition",
        "sensitivity": "low"
      },
      {
        "t": 1012,
        "ts": "2026-09-14T16:52:04Z",
        "action": "github.pr.review",
        "sensitivity": "low"
      }
    ],
    "context": [],
    "risk": [
      {
        "t": 0,
        "risk": 13
      },
      {
        "t": 207,
        "risk": 13
      },
      {
        "t": 208,
        "risk": 33
      },
      {
        "t": 217,
        "risk": 54
      },
      {
        "t": 225,
        "risk": 74
      },
      {
        "t": 1439,
        "risk": 74
      }
    ]
  },
  {
    "subjectId": "subject_1188",
    "session": [
      {
        "t": 612,
        "ts": "2026-09-14T10:12:24Z",
        "action": "okta.session.start",
        "sensitivity": "low",
        "note": "Corporate ASN · Bengaluru"
      }
    ],
    "trajectory": [
      {
        "t": 634,
        "ts": "2026-09-14T10:34:58Z",
        "action": "bigquery.job.query",
        "resource": "events.sessions",
        "sensitivity": "high",
        "note": "events.sessions · 41M rows scanned"
      },
      {
        "t": 650,
        "ts": "2026-09-14T10:50:50Z",
        "action": "gcs.object.export",
        "resource": "gs://analytics-export",
        "sensitivity": "critical",
        "note": "gs://analytics-export · 2.1 GB"
      },
      {
        "t": 663,
        "ts": "2026-09-14T11:03:21Z",
        "action": "gcs.bucket.share",
        "resource": "Unaffiliated project",
        "sensitivity": "critical",
        "note": "Unaffiliated project · first ever",
        "firstEver": true
      },
      {
        "t": 676,
        "ts": "2026-09-14T11:16:52Z",
        "action": "slack.channel.message",
        "sensitivity": "low"
      },
      {
        "t": 790,
        "ts": "2026-09-14T13:10:10Z",
        "action": "confluence.page.view",
        "sensitivity": "low"
      },
      {
        "t": 905,
        "ts": "2026-09-14T15:05:35Z",
        "action": "jira.issue.transition",
        "sensitivity": "low"
      },
      {
        "t": 1012,
        "ts": "2026-09-14T16:52:04Z",
        "action": "github.pr.review",
        "sensitivity": "low"
      }
    ],
    "context": [
      {
        "from": 484,
        "to": 649,
        "recordId": "TICKET-3288",
        "label": "On-call rotation · scope does not name the resource touched",
        "verdict": "partial"
      }
    ],
    "risk": [
      {
        "t": 0,
        "risk": 13
      },
      {
        "t": 633,
        "risk": 13
      },
      {
        "t": 634,
        "risk": 32
      },
      {
        "t": 650,
        "risk": 52
      },
      {
        "t": 663,
        "risk": 71
      },
      {
        "t": 1439,
        "risk": 71
      }
    ]
  },
  {
    "subjectId": "subject_6302",
    "session": [
      {
        "t": 612,
        "ts": "2026-09-14T10:12:24Z",
        "action": "okta.session.start",
        "sensitivity": "low",
        "note": "Corporate ASN · Bengaluru",
        "asnChange": true,
        "firstEver": true
      }
    ],
    "trajectory": [
      {
        "t": 634,
        "ts": "2026-09-14T10:34:58Z",
        "action": "bigquery.job.query",
        "resource": "events.sessions",
        "sensitivity": "high",
        "note": "events.sessions · 41M rows scanned"
      },
      {
        "t": 650,
        "ts": "2026-09-14T10:50:50Z",
        "action": "gcs.object.export",
        "resource": "gs://analytics-export",
        "sensitivity": "critical",
        "note": "gs://analytics-export · 2.1 GB"
      },
      {
        "t": 663,
        "ts": "2026-09-14T11:03:21Z",
        "action": "gcs.bucket.share",
        "resource": "Unaffiliated project",
        "sensitivity": "critical",
        "note": "Unaffiliated project · first ever",
        "firstEver": true
      },
      {
        "t": 676,
        "ts": "2026-09-14T11:16:52Z",
        "action": "slack.channel.message",
        "sensitivity": "low"
      },
      {
        "t": 790,
        "ts": "2026-09-14T13:10:10Z",
        "action": "confluence.page.view",
        "sensitivity": "low"
      },
      {
        "t": 905,
        "ts": "2026-09-14T15:05:35Z",
        "action": "jira.issue.transition",
        "sensitivity": "low"
      },
      {
        "t": 1012,
        "ts": "2026-09-14T16:52:04Z",
        "action": "github.pr.review",
        "sensitivity": "low"
      }
    ],
    "context": [],
    "risk": [
      {
        "t": 0,
        "risk": 12
      },
      {
        "t": 633,
        "risk": 12
      },
      {
        "t": 634,
        "risk": 31
      },
      {
        "t": 650,
        "risk": 50
      },
      {
        "t": 663,
        "risk": 69
      },
      {
        "t": 1439,
        "risk": 69
      }
    ]
  },
  {
    "subjectId": "subject_3914",
    "session": [
      {
        "t": 585,
        "ts": "2026-09-14T09:45:15Z",
        "action": "okta.session.start",
        "sensitivity": "low",
        "note": "Corporate ASN · Pune"
      }
    ],
    "trajectory": [
      {
        "t": 619,
        "ts": "2026-09-14T10:19:13Z",
        "action": "zendesk.ticket.bulk_export",
        "resource": "1,204 tickets",
        "sensitivity": "high",
        "note": "1,204 tickets · CSV"
      },
      {
        "t": 632,
        "ts": "2026-09-14T10:32:44Z",
        "action": "gdrive.file.download",
        "resource": "Support — escalations Q3",
        "sensitivity": "medium",
        "note": "Support — escalations Q3"
      },
      {
        "t": 648,
        "ts": "2026-09-14T10:48:36Z",
        "action": "gdrive.folder.share",
        "resource": "Link sharing enabled",
        "sensitivity": "critical",
        "note": "Link sharing enabled · first ever",
        "firstEver": true
      },
      {
        "t": 676,
        "ts": "2026-09-14T11:16:52Z",
        "action": "slack.channel.message",
        "sensitivity": "low"
      },
      {
        "t": 790,
        "ts": "2026-09-14T13:10:10Z",
        "action": "confluence.page.view",
        "sensitivity": "low"
      },
      {
        "t": 905,
        "ts": "2026-09-14T15:05:35Z",
        "action": "jira.issue.transition",
        "sensitivity": "low"
      },
      {
        "t": 1012,
        "ts": "2026-09-14T16:52:04Z",
        "action": "github.pr.review",
        "sensitivity": "low"
      }
    ],
    "context": [
      {
        "from": 469,
        "to": 634,
        "recordId": "TICKET-3314",
        "label": "On-call rotation · scope does not name the resource touched",
        "verdict": "partial"
      }
    ],
    "risk": [
      {
        "t": 0,
        "risk": 12
      },
      {
        "t": 618,
        "risk": 12
      },
      {
        "t": 619,
        "risk": 30
      },
      {
        "t": 632,
        "risk": 48
      },
      {
        "t": 648,
        "risk": 66
      },
      {
        "t": 1439,
        "risk": 66
      }
    ]
  },
  {
    "subjectId": "subject_8125",
    "session": [
      {
        "t": 192,
        "ts": "2026-09-14T03:12:24Z",
        "action": "okta.session.start",
        "sensitivity": "medium",
        "note": "03:12 local · outside working envelope",
        "asnChange": true,
        "firstEver": true
      }
    ],
    "trajectory": [
      {
        "t": 201,
        "ts": "2026-09-14T03:21:27Z",
        "action": "netsuite.report.run",
        "resource": "Vendor master",
        "sensitivity": "high",
        "note": "Vendor master · full extract"
      },
      {
        "t": 209,
        "ts": "2026-09-14T03:29:23Z",
        "action": "netsuite.export.csv",
        "resource": "vendors_full.csv",
        "sensitivity": "critical",
        "note": "vendors_full.csv · 8,410 rows"
      },
      {
        "t": 220,
        "ts": "2026-09-14T03:40:40Z",
        "action": "gdrive.file.upload",
        "resource": "Personal drive",
        "sensitivity": "critical",
        "note": "Personal drive · first ever",
        "firstEver": true
      },
      {
        "t": 570,
        "ts": "2026-09-14T09:30:30Z",
        "action": "jira.issue.comment",
        "sensitivity": "low"
      },
      {
        "t": 676,
        "ts": "2026-09-14T11:16:52Z",
        "action": "slack.channel.message",
        "sensitivity": "low"
      },
      {
        "t": 790,
        "ts": "2026-09-14T13:10:10Z",
        "action": "confluence.page.view",
        "sensitivity": "low"
      },
      {
        "t": 905,
        "ts": "2026-09-14T15:05:35Z",
        "action": "jira.issue.transition",
        "sensitivity": "low"
      },
      {
        "t": 1012,
        "ts": "2026-09-14T16:52:04Z",
        "action": "github.pr.review",
        "sensitivity": "low"
      }
    ],
    "context": [
      {
        "from": 51,
        "to": 211,
        "recordId": "TICKET-3025",
        "label": "On-call rotation · scope does not name the resource touched",
        "verdict": "partial"
      }
    ],
    "risk": [
      {
        "t": 0,
        "risk": 11
      },
      {
        "t": 200,
        "risk": 11
      },
      {
        "t": 201,
        "risk": 28
      },
      {
        "t": 209,
        "risk": 44
      },
      {
        "t": 220,
        "risk": 61
      },
      {
        "t": 1439,
        "risk": 61
      }
    ]
  },
  {
    "subjectId": "subject_4407",
    "session": [
      {
        "t": 628,
        "ts": "2026-09-14T10:28:16Z",
        "action": "okta.session.start",
        "sensitivity": "low",
        "note": "Corporate ASN · Chennai",
        "asnChange": true,
        "firstEver": true
      }
    ],
    "trajectory": [
      {
        "t": 570,
        "ts": "2026-09-14T09:30:30Z",
        "action": "jira.issue.comment",
        "sensitivity": "low"
      },
      {
        "t": 642,
        "ts": "2026-09-14T10:42:54Z",
        "action": "gws.mail.filter.create",
        "resource": "Auto-forward rule",
        "sensitivity": "high",
        "note": "Auto-forward rule · external domain"
      },
      {
        "t": 654,
        "ts": "2026-09-14T10:54:18Z",
        "action": "gws.mail.send_external",
        "resource": "4 unaffiliated domains",
        "sensitivity": "critical",
        "note": "4 unaffiliated domains · first ever",
        "firstEver": true
      },
      {
        "t": 668,
        "ts": "2026-09-14T11:08:56Z",
        "action": "gws.contact.export",
        "resource": "Directory export",
        "sensitivity": "medium",
        "note": "Directory export · 612 records"
      },
      {
        "t": 676,
        "ts": "2026-09-14T11:16:52Z",
        "action": "slack.channel.message",
        "sensitivity": "low"
      },
      {
        "t": 790,
        "ts": "2026-09-14T13:10:10Z",
        "action": "confluence.page.view",
        "sensitivity": "low"
      },
      {
        "t": 905,
        "ts": "2026-09-14T15:05:35Z",
        "action": "jira.issue.transition",
        "sensitivity": "low"
      },
      {
        "t": 1012,
        "ts": "2026-09-14T16:52:04Z",
        "action": "github.pr.review",
        "sensitivity": "low"
      }
    ],
    "context": [],
    "risk": [
      {
        "t": 0,
        "risk": 10
      },
      {
        "t": 641,
        "risk": 10
      },
      {
        "t": 642,
        "risk": 26
      },
      {
        "t": 654,
        "risk": 42
      },
      {
        "t": 668,
        "risk": 58
      },
      {
        "t": 1439,
        "risk": 58
      }
    ]
  },
  {
    "subjectId": "subject_9663",
    "session": [
      {
        "t": 505,
        "ts": "2026-09-14T08:25:55Z",
        "action": "okta.session.start",
        "sensitivity": "low",
        "note": "Corporate ASN · Hyderabad",
        "asnChange": true,
        "firstEver": true
      }
    ],
    "trajectory": [
      {
        "t": 517,
        "ts": "2026-09-14T08:37:19Z",
        "action": "aws.iam.policy.put",
        "resource": "AdministratorAccess-scoped inline policy",
        "sensitivity": "critical",
        "note": "AdministratorAccess-scoped inline policy"
      },
      {
        "t": 523,
        "ts": "2026-09-14T08:43:01Z",
        "action": "aws.iam.role.attach",
        "resource": "svc-batch-runner",
        "sensitivity": "high",
        "note": "svc-batch-runner · privilege widened"
      },
      {
        "t": 536,
        "ts": "2026-09-14T08:56:32Z",
        "action": "aws.s3.get_object",
        "resource": "s3://finance-close-2026",
        "sensitivity": "medium",
        "note": "s3://finance-close-2026 · first ever",
        "firstEver": true
      },
      {
        "t": 570,
        "ts": "2026-09-14T09:30:30Z",
        "action": "jira.issue.comment",
        "sensitivity": "low"
      },
      {
        "t": 676,
        "ts": "2026-09-14T11:16:52Z",
        "action": "slack.channel.message",
        "sensitivity": "low"
      },
      {
        "t": 790,
        "ts": "2026-09-14T13:10:10Z",
        "action": "confluence.page.view",
        "sensitivity": "low"
      },
      {
        "t": 905,
        "ts": "2026-09-14T15:05:35Z",
        "action": "jira.issue.transition",
        "sensitivity": "low"
      },
      {
        "t": 1012,
        "ts": "2026-09-14T16:52:04Z",
        "action": "github.pr.review",
        "sensitivity": "low"
      }
    ],
    "context": [
      {
        "from": 367,
        "to": 527,
        "recordId": "TICKET-3663",
        "label": "On-call rotation · scope does not name the resource touched",
        "verdict": "partial"
      }
    ],
    "risk": [
      {
        "t": 0,
        "risk": 10
      },
      {
        "t": 516,
        "risk": 10
      },
      {
        "t": 517,
        "risk": 25
      },
      {
        "t": 523,
        "risk": 40
      },
      {
        "t": 536,
        "risk": 55
      },
      {
        "t": 1439,
        "risk": 55
      }
    ]
  },
  {
    "subjectId": "subject_2258",
    "session": [
      {
        "t": 505,
        "ts": "2026-09-14T08:25:55Z",
        "action": "okta.session.start",
        "sensitivity": "low",
        "note": "Corporate ASN · Hyderabad",
        "asnChange": true,
        "firstEver": true
      }
    ],
    "trajectory": [
      {
        "t": 517,
        "ts": "2026-09-14T08:37:19Z",
        "action": "aws.iam.policy.put",
        "resource": "AdministratorAccess-scoped inline policy",
        "sensitivity": "critical",
        "note": "AdministratorAccess-scoped inline policy"
      },
      {
        "t": 523,
        "ts": "2026-09-14T08:43:01Z",
        "action": "aws.iam.role.attach",
        "resource": "svc-batch-runner",
        "sensitivity": "high",
        "note": "svc-batch-runner · privilege widened"
      },
      {
        "t": 536,
        "ts": "2026-09-14T08:56:32Z",
        "action": "aws.s3.get_object",
        "resource": "s3://finance-close-2026",
        "sensitivity": "medium",
        "note": "s3://finance-close-2026 · first ever",
        "firstEver": true
      },
      {
        "t": 570,
        "ts": "2026-09-14T09:30:30Z",
        "action": "jira.issue.comment",
        "sensitivity": "low"
      },
      {
        "t": 676,
        "ts": "2026-09-14T11:16:52Z",
        "action": "slack.channel.message",
        "sensitivity": "low"
      },
      {
        "t": 790,
        "ts": "2026-09-14T13:10:10Z",
        "action": "confluence.page.view",
        "sensitivity": "low"
      },
      {
        "t": 905,
        "ts": "2026-09-14T15:05:35Z",
        "action": "jira.issue.transition",
        "sensitivity": "low"
      },
      {
        "t": 1012,
        "ts": "2026-09-14T16:52:04Z",
        "action": "github.pr.review",
        "sensitivity": "low"
      }
    ],
    "context": [
      {
        "from": 367,
        "to": 527,
        "recordId": "TICKET-3458",
        "label": "On-call rotation · scope does not name the resource touched",
        "verdict": "partial"
      }
    ],
    "risk": [
      {
        "t": 0,
        "risk": 9
      },
      {
        "t": 516,
        "risk": 9
      },
      {
        "t": 517,
        "risk": 22
      },
      {
        "t": 523,
        "risk": 36
      },
      {
        "t": 536,
        "risk": 49
      },
      {
        "t": 1439,
        "risk": 49
      }
    ]
  },
  {
    "subjectId": "subject_7015",
    "session": [
      {
        "t": 640,
        "ts": "2026-09-14T10:40:40Z",
        "action": "okta.session.start",
        "sensitivity": "low",
        "note": "Corporate ASN · Bengaluru",
        "asnChange": true,
        "firstEver": true
      }
    ],
    "trajectory": [
      {
        "t": 570,
        "ts": "2026-09-14T09:30:30Z",
        "action": "jira.issue.comment",
        "sensitivity": "low"
      },
      {
        "t": 658,
        "ts": "2026-09-14T10:58:46Z",
        "action": "gdrive.folder.list",
        "resource": "Shared — Data Platform",
        "sensitivity": "low",
        "note": "Shared — Data Platform"
      },
      {
        "t": 676,
        "ts": "2026-09-14T11:16:52Z",
        "action": "gdrive.file.download",
        "resource": "214 files",
        "sensitivity": "high",
        "note": "214 files · 40 minutes"
      },
      {
        "t": 698,
        "ts": "2026-09-14T11:38:26Z",
        "action": "dropbox.folder.sync",
        "resource": "Personal account",
        "sensitivity": "critical",
        "note": "Personal account · first ever",
        "firstEver": true
      },
      {
        "t": 790,
        "ts": "2026-09-14T13:10:10Z",
        "action": "confluence.page.view",
        "sensitivity": "low"
      },
      {
        "t": 905,
        "ts": "2026-09-14T15:05:35Z",
        "action": "jira.issue.transition",
        "sensitivity": "low"
      },
      {
        "t": 1012,
        "ts": "2026-09-14T16:52:04Z",
        "action": "github.pr.review",
        "sensitivity": "low"
      }
    ],
    "context": [],
    "risk": [
      {
        "t": 0,
        "risk": 8
      },
      {
        "t": 657,
        "risk": 8
      },
      {
        "t": 658,
        "risk": 20
      },
      {
        "t": 676,
        "risk": 32
      },
      {
        "t": 698,
        "risk": 44
      },
      {
        "t": 1439,
        "risk": 44
      }
    ]
  },
  {
    "subjectId": "subject_5871",
    "session": [
      {
        "t": 561,
        "ts": "2026-09-14T09:21:27Z",
        "action": "okta.session.start",
        "sensitivity": "low",
        "note": "Corporate ASN · Mumbai",
        "asnChange": true,
        "firstEver": true
      }
    ],
    "trajectory": [
      {
        "t": 582,
        "ts": "2026-09-14T09:42:54Z",
        "action": "netsuite.search.saved_run",
        "resource": "Open invoices",
        "sensitivity": "low",
        "note": "Open invoices · saved search"
      },
      {
        "t": 600,
        "ts": "2026-09-14T10:00:00Z",
        "action": "netsuite.record.fetch",
        "resource": "Sequential record reads",
        "sensitivity": "medium",
        "note": "Sequential record reads"
      },
      {
        "t": 615,
        "ts": "2026-09-14T10:15:45Z",
        "action": "netsuite.export.csv",
        "resource": "Close pack",
        "sensitivity": "high",
        "note": "Close pack · 1 file"
      },
      {
        "t": 676,
        "ts": "2026-09-14T11:16:52Z",
        "action": "slack.channel.message",
        "sensitivity": "low"
      },
      {
        "t": 790,
        "ts": "2026-09-14T13:10:10Z",
        "action": "confluence.page.view",
        "sensitivity": "low"
      },
      {
        "t": 905,
        "ts": "2026-09-14T15:05:35Z",
        "action": "jira.issue.transition",
        "sensitivity": "low"
      },
      {
        "t": 1012,
        "ts": "2026-09-14T16:52:04Z",
        "action": "github.pr.review",
        "sensitivity": "low"
      }
    ],
    "context": [
      {
        "from": 432,
        "to": 599,
        "recordId": "TICKET-3471",
        "label": "On-call rotation · scope does not name the resource touched",
        "verdict": "partial"
      }
    ],
    "risk": [
      {
        "t": 0,
        "risk": 7
      },
      {
        "t": 581,
        "risk": 7
      },
      {
        "t": 582,
        "risk": 17
      },
      {
        "t": 600,
        "risk": 28
      },
      {
        "t": 615,
        "risk": 38
      },
      {
        "t": 1439,
        "risk": 38
      }
    ]
  },
  {
    "subjectId": "subject_3340",
    "session": [
      {
        "t": 549,
        "ts": "2026-09-14T09:09:03Z",
        "action": "okta.session.start",
        "sensitivity": "low",
        "note": "Corporate ASN · Bengaluru",
        "asnChange": true,
        "firstEver": true
      }
    ],
    "trajectory": [
      {
        "t": 576,
        "ts": "2026-09-14T09:36:12Z",
        "action": "zendesk.ticket.bulk_export",
        "resource": "96 tickets",
        "sensitivity": "high",
        "note": "96 tickets · CSV, within ticket scope"
      },
      {
        "t": 593,
        "ts": "2026-09-14T09:53:11Z",
        "action": "gdrive.file.download",
        "resource": "Support — refund audit pack",
        "sensitivity": "medium",
        "note": "Support — refund audit pack"
      },
      {
        "t": 610,
        "ts": "2026-09-14T10:10:10Z",
        "action": "zendesk.macro.apply",
        "resource": "Bulk macro",
        "sensitivity": "low",
        "note": "Bulk macro · refund-followup"
      },
      {
        "t": 676,
        "ts": "2026-09-14T11:16:52Z",
        "action": "slack.channel.message",
        "sensitivity": "low"
      },
      {
        "t": 790,
        "ts": "2026-09-14T13:10:10Z",
        "action": "confluence.page.view",
        "sensitivity": "low"
      },
      {
        "t": 905,
        "ts": "2026-09-14T15:05:35Z",
        "action": "jira.issue.transition",
        "sensitivity": "low"
      },
      {
        "t": 1012,
        "ts": "2026-09-14T16:52:04Z",
        "action": "github.pr.review",
        "sensitivity": "low"
      }
    ],
    "context": [
      {
        "from": 0,
        "to": 1439,
        "recordId": "TICKET-3640",
        "label": "Scope-matched ticket · assigned by another identity",
        "verdict": "authorised"
      }
    ],
    "risk": [
      {
        "t": 0,
        "risk": 6
      },
      {
        "t": 575,
        "risk": 6
      },
      {
        "t": 576,
        "risk": 14
      },
      {
        "t": 593,
        "risk": 23
      },
      {
        "t": 610,
        "risk": 31
      },
      {
        "t": 1439,
        "risk": 31
      }
    ]
  }
];
