/**
 * GENERATED by scripts/generate-population.mjs — do not edit by hand.
 * Committed deliberately: nothing randomises at runtime, so the numbers in the
 * demo video and the numbers a judge sees are the same numbers (PRD §6).
 */
import type { Suppression } from "./types";

/** Suppressed, not discarded (PRD §5.5). One row is UNDER REVIEW. */
export const SUPPRESSIONS: Suppression[] = [
  {
    "id": "sup-000",
    "ts": "2026-09-14T10:15:41Z",
    "subjectPseudonym": "#8830",
    "anomaly": "First-ever repository access — payments-core",
    "suppressedBy": "Jira",
    "reasonCode": "SCOPE_MATCHED_TICKET",
    "reviewable": true,
    "record": {
      "recordId": "TICKET-4471",
      "createdBy": "subject_5530",
      "createdAt": "2026-09-13T09:12:00Z",
      "scope": "payments-core"
    }
  },
  {
    "id": "sup-028",
    "ts": "2026-09-14T19:54:11Z",
    "subjectPseudonym": "#2345",
    "anomaly": "Cross-department graph edge",
    "suppressedBy": "Workday",
    "reasonCode": "ROLE_CHANGE",
    "reviewable": true,
    "record": {
      "recordId": "HR-7889",
      "createdBy": "subject_9520",
      "createdAt": "2026-09-14T04:05:00Z",
      "scope": "support-tooling"
    }
  },
  {
    "id": "sup-019",
    "ts": "2026-09-14T19:16:22Z",
    "subjectPseudonym": "#6769",
    "anomaly": "New device fingerprint",
    "suppressedBy": "Workday",
    "reasonCode": "APPROVED_TRAVEL",
    "reviewable": true,
    "record": {
      "recordId": "HR-1410",
      "createdBy": "subject_1397",
      "createdAt": "2026-09-13T13:04:00Z",
      "scope": "ledger-api"
    }
  },
  {
    "id": "sup-rev",
    "ts": "2026-09-14T14:47:09Z",
    "subjectPseudonym": "#2071",
    "anomaly": "First-ever repository access — payments-core",
    "suppressedBy": "Jira",
    "reasonCode": "SCOPE_MATCHED_TICKET",
    "reviewable": true,
    "underReview": true,
    "record": {
      "recordId": "TICKET-9920",
      "createdBy": "subject_2071",
      "createdAt": "2026-09-14T14:07:00Z",
      "scope": "payments-core"
    },
    "linkedSubjectId": "subject_2071"
  },
  {
    "id": "sup-011",
    "ts": "2026-09-14T18:59:51Z",
    "subjectPseudonym": "#4002",
    "anomaly": "External share created",
    "suppressedBy": "Jira",
    "reasonCode": "SCOPE_MATCHED_TICKET",
    "reviewable": true,
    "record": {
      "recordId": "TICKET-9046",
      "createdBy": "subject_2232",
      "createdAt": "2026-09-12T09:32:00Z",
      "scope": "payments-core"
    }
  },
  {
    "id": "sup-026",
    "ts": "2026-09-14T18:13:51Z",
    "subjectPseudonym": "#2524",
    "anomaly": "Composition drift, JSD 0.21",
    "suppressedBy": "PagerDuty",
    "reasonCode": "ON_CALL_ROTATION",
    "reviewable": true,
    "record": {
      "recordId": "ROTA-6782",
      "createdBy": "subject_1547",
      "createdAt": "2026-09-14T04:21:00Z",
      "scope": "analytics-dbt"
    }
  },
  {
    "id": "sup-015",
    "ts": "2026-09-14T16:57:26Z",
    "subjectPseudonym": "#8810",
    "anomaly": "Bulk permission read",
    "suppressedBy": "Workday",
    "reasonCode": "ROLE_CHANGE",
    "reviewable": true,
    "record": {
      "recordId": "HR-8221",
      "createdBy": "subject_7911",
      "createdAt": "2026-09-12T00:45:00Z",
      "scope": "support-tooling"
    }
  },
  {
    "id": "sup-003",
    "ts": "2026-09-14T16:31:57Z",
    "subjectPseudonym": "#3338",
    "anomaly": "First-ever repository access",
    "suppressedBy": "Workday",
    "reasonCode": "ROLE_CHANGE",
    "reviewable": true,
    "record": {
      "recordId": "HR-7873",
      "createdBy": "subject_6735",
      "createdAt": "2026-09-14T00:34:00Z",
      "scope": "analytics-dbt"
    }
  },
  {
    "id": "sup-038",
    "ts": "2026-09-14T16:12:54Z",
    "subjectPseudonym": "#4002",
    "anomaly": "Cross-department graph edge",
    "suppressedBy": "Okta",
    "reasonCode": "NEW_DEVICE_APPROVED",
    "reviewable": true,
    "record": {
      "recordId": "HR-6805",
      "createdBy": "subject_9331",
      "createdAt": "2026-09-12T00:59:00Z",
      "scope": "analytics-dbt"
    }
  },
  {
    "id": "sup-005",
    "ts": "2026-09-14T16:08:52Z",
    "subjectPseudonym": "#1681",
    "anomaly": "Cross-department graph edge",
    "suppressedBy": "PagerDuty",
    "reasonCode": "ON_CALL_ROTATION",
    "reviewable": true,
    "record": {
      "recordId": "ROTA-1771",
      "createdBy": "subject_8603",
      "createdAt": "2026-09-14T06:50:00Z",
      "scope": "analytics-dbt"
    }
  },
  {
    "id": "sup-008",
    "ts": "2026-09-14T16:05:30Z",
    "subjectPseudonym": "#6817",
    "anomaly": "New device fingerprint",
    "suppressedBy": "PagerDuty",
    "reasonCode": "ON_CALL_ROTATION",
    "reviewable": true,
    "record": {
      "recordId": "ROTA-8106",
      "createdBy": "subject_5132",
      "createdAt": "2026-09-12T09:23:00Z",
      "scope": "ledger-api"
    }
  },
  {
    "id": "sup-031",
    "ts": "2026-09-14T15:56:31Z",
    "subjectPseudonym": "#1927",
    "anomaly": "Composition drift, JSD 0.21",
    "suppressedBy": "Jira",
    "reasonCode": "SCOPE_MATCHED_TICKET",
    "reviewable": true,
    "record": {
      "recordId": "TICKET-4221",
      "createdBy": "subject_8313",
      "createdAt": "2026-09-13T17:15:00Z",
      "scope": "payments-core"
    }
  },
  {
    "id": "sup-029",
    "ts": "2026-09-14T15:06:03Z",
    "subjectPseudonym": "#9685",
    "anomaly": "New device fingerprint",
    "suppressedBy": "Workday",
    "reasonCode": "ROLE_CHANGE",
    "reviewable": true,
    "record": {
      "recordId": "HR-6041",
      "createdBy": "subject_7817",
      "createdAt": "2026-09-13T04:34:00Z",
      "scope": "ledger-api"
    }
  },
  {
    "id": "sup-009",
    "ts": "2026-09-14T14:34:04Z",
    "subjectPseudonym": "#2524",
    "anomaly": "Cross-department graph edge",
    "suppressedBy": "Workday",
    "reasonCode": "ROLE_CHANGE",
    "reviewable": true,
    "record": {
      "recordId": "HR-1115",
      "createdBy": "subject_8497",
      "createdAt": "2026-09-14T00:01:00Z",
      "scope": "analytics-dbt"
    }
  },
  {
    "id": "sup-030",
    "ts": "2026-09-14T14:30:46Z",
    "subjectPseudonym": "#1221",
    "anomaly": "Unseen ASN",
    "suppressedBy": "Okta",
    "reasonCode": "NEW_DEVICE_APPROVED",
    "reviewable": true,
    "record": {
      "recordId": "HR-8538",
      "createdBy": "subject_3610",
      "createdAt": "2026-09-12T06:17:00Z",
      "scope": "analytics-dbt"
    }
  },
  {
    "id": "sup-018",
    "ts": "2026-09-14T14:03:47Z",
    "subjectPseudonym": "#2581",
    "anomaly": "Composition drift, JSD 0.21",
    "suppressedBy": "PagerDuty",
    "reasonCode": "ON_CALL_ROTATION",
    "reviewable": true,
    "record": {
      "recordId": "ROTA-3869",
      "createdBy": "subject_2609",
      "createdAt": "2026-09-12T02:42:00Z",
      "scope": "support-tooling"
    }
  },
  {
    "id": "sup-014",
    "ts": "2026-09-14T13:04:56Z",
    "subjectPseudonym": "#3338",
    "anomaly": "Cross-department graph edge",
    "suppressedBy": "PagerDuty",
    "reasonCode": "ON_CALL_ROTATION",
    "reviewable": true,
    "record": {
      "recordId": "ROTA-5839",
      "createdBy": "subject_4204",
      "createdAt": "2026-09-14T08:14:00Z",
      "scope": "billing-web"
    }
  },
  {
    "id": "sup-023",
    "ts": "2026-09-14T12:42:44Z",
    "subjectPseudonym": "#7762",
    "anomaly": "Archive creation, 62 files",
    "suppressedBy": "PagerDuty",
    "reasonCode": "ON_CALL_ROTATION",
    "reviewable": true,
    "record": {
      "recordId": "ROTA-3721",
      "createdBy": "subject_1822",
      "createdAt": "2026-09-14T03:05:00Z",
      "scope": "support-tooling"
    }
  },
  {
    "id": "sup-036",
    "ts": "2026-09-14T11:30:23Z",
    "subjectPseudonym": "#5507",
    "anomaly": "Off-hours authentication",
    "suppressedBy": "Workday",
    "reasonCode": "ROLE_CHANGE",
    "reviewable": true,
    "record": {
      "recordId": "HR-3455",
      "createdBy": "subject_9137",
      "createdAt": "2026-09-13T00:18:00Z",
      "scope": "ledger-api"
    }
  },
  {
    "id": "sup-033",
    "ts": "2026-09-14T10:40:51Z",
    "subjectPseudonym": "#6100",
    "anomaly": "First-ever repository access",
    "suppressedBy": "Workday",
    "reasonCode": "ROLE_CHANGE",
    "reviewable": true,
    "record": {
      "recordId": "HR-6614",
      "createdBy": "subject_8608",
      "createdAt": "2026-09-13T14:01:00Z",
      "scope": "payments-core"
    }
  },
  {
    "id": "sup-024",
    "ts": "2026-09-14T10:30:25Z",
    "subjectPseudonym": "#8310",
    "anomaly": "Bulk permission read",
    "suppressedBy": "Workday",
    "reasonCode": "APPROVED_TRAVEL",
    "reviewable": true,
    "record": {
      "recordId": "HR-2207",
      "createdBy": "subject_7654",
      "createdAt": "2026-09-13T13:04:00Z",
      "scope": "support-tooling"
    }
  },
  {
    "id": "sup-012",
    "ts": "2026-09-14T10:03:19Z",
    "subjectPseudonym": "#9942",
    "anomaly": "Cross-department graph edge",
    "suppressedBy": "Jira",
    "reasonCode": "SCOPE_MATCHED_TICKET",
    "reviewable": true,
    "record": {
      "recordId": "TICKET-6956",
      "createdBy": "subject_3073",
      "createdAt": "2026-09-14T18:43:00Z",
      "scope": "analytics-dbt"
    }
  },
  {
    "id": "sup-007",
    "ts": "2026-09-14T09:21:04Z",
    "subjectPseudonym": "#6808",
    "anomaly": "First-ever repository access",
    "suppressedBy": "PagerDuty",
    "reasonCode": "ON_CALL_ROTATION",
    "reviewable": true,
    "record": {
      "recordId": "ROTA-9866",
      "createdBy": "subject_9026",
      "createdAt": "2026-09-12T09:51:00Z",
      "scope": "payments-core"
    }
  },
  {
    "id": "sup-032",
    "ts": "2026-09-14T08:52:05Z",
    "subjectPseudonym": "#1927",
    "anomaly": "Unseen ASN",
    "suppressedBy": "Workday",
    "reasonCode": "ROLE_CHANGE",
    "reviewable": true,
    "record": {
      "recordId": "HR-5284",
      "createdBy": "subject_6322",
      "createdAt": "2026-09-14T01:42:00Z",
      "scope": "billing-web"
    }
  },
  {
    "id": "sup-016",
    "ts": "2026-09-14T08:33:48Z",
    "subjectPseudonym": "#1927",
    "anomaly": "Off-hours authentication",
    "suppressedBy": "Workday",
    "reasonCode": "APPROVED_TRAVEL",
    "reviewable": true,
    "record": {
      "recordId": "HR-5682",
      "createdBy": "subject_4757",
      "createdAt": "2026-09-12T07:52:00Z",
      "scope": "support-tooling"
    }
  },
  {
    "id": "sup-002",
    "ts": "2026-09-14T08:23:08Z",
    "subjectPseudonym": "#9298",
    "anomaly": "Unseen ASN",
    "suppressedBy": "Workday",
    "reasonCode": "APPROVED_TRAVEL",
    "reviewable": true,
    "record": {
      "recordId": "HR-1097",
      "createdBy": "subject_3988",
      "createdAt": "2026-09-12T00:34:00Z",
      "scope": "ledger-api"
    }
  },
  {
    "id": "sup-010",
    "ts": "2026-09-14T08:07:57Z",
    "subjectPseudonym": "#2371",
    "anomaly": "New device fingerprint",
    "suppressedBy": "Okta",
    "reasonCode": "NEW_DEVICE_APPROVED",
    "reviewable": true,
    "record": {
      "recordId": "HR-9127",
      "createdBy": "subject_7411",
      "createdAt": "2026-09-12T00:14:00Z",
      "scope": "analytics-dbt"
    }
  },
  {
    "id": "sup-021",
    "ts": "2026-09-14T07:58:27Z",
    "subjectPseudonym": "#7481",
    "anomaly": "Volumetric deviation, Z = +3.4",
    "suppressedBy": "Okta",
    "reasonCode": "NEW_DEVICE_APPROVED",
    "reviewable": true,
    "record": {
      "recordId": "HR-2089",
      "createdBy": "subject_8832",
      "createdAt": "2026-09-14T00:23:00Z",
      "scope": "payments-core"
    }
  },
  {
    "id": "sup-039",
    "ts": "2026-09-14T07:42:51Z",
    "subjectPseudonym": "#2683",
    "anomaly": "Unseen ASN",
    "suppressedBy": "Okta",
    "reasonCode": "NEW_DEVICE_APPROVED",
    "reviewable": true,
    "record": {
      "recordId": "HR-4650",
      "createdBy": "subject_7118",
      "createdAt": "2026-09-14T00:58:00Z",
      "scope": "infra-terraform"
    }
  },
  {
    "id": "sup-027",
    "ts": "2026-09-14T07:40:48Z",
    "subjectPseudonym": "#9685",
    "anomaly": "First-ever repository access",
    "suppressedBy": "Okta",
    "reasonCode": "NEW_DEVICE_APPROVED",
    "reviewable": true,
    "record": {
      "recordId": "HR-7797",
      "createdBy": "subject_4006",
      "createdAt": "2026-09-12T09:47:00Z",
      "scope": "billing-web"
    }
  },
  {
    "id": "sup-037",
    "ts": "2026-09-14T07:36:56Z",
    "subjectPseudonym": "#2586",
    "anomaly": "New device fingerprint",
    "suppressedBy": "Workday",
    "reasonCode": "APPROVED_TRAVEL",
    "reviewable": true,
    "record": {
      "recordId": "HR-4370",
      "createdBy": "subject_8005",
      "createdAt": "2026-09-12T15:34:00Z",
      "scope": "billing-web"
    }
  },
  {
    "id": "sup-035",
    "ts": "2026-09-14T07:36:09Z",
    "subjectPseudonym": "#3015",
    "anomaly": "Volumetric deviation, Z = +3.4",
    "suppressedBy": "Workday",
    "reasonCode": "ROLE_CHANGE",
    "reviewable": true,
    "record": {
      "recordId": "HR-7518",
      "createdBy": "subject_1782",
      "createdAt": "2026-09-14T00:34:00Z",
      "scope": "analytics-dbt"
    }
  },
  {
    "id": "sup-034",
    "ts": "2026-09-14T06:19:55Z",
    "subjectPseudonym": "#1074",
    "anomaly": "Composition drift, JSD 0.21",
    "suppressedBy": "Jira",
    "reasonCode": "SCOPE_MATCHED_TICKET",
    "reviewable": true,
    "record": {
      "recordId": "TICKET-8267",
      "createdBy": "subject_2558",
      "createdAt": "2026-09-12T00:49:00Z",
      "scope": "ledger-api"
    }
  },
  {
    "id": "sup-022",
    "ts": "2026-09-14T05:58:27Z",
    "subjectPseudonym": "#1000",
    "anomaly": "New device fingerprint",
    "suppressedBy": "PagerDuty",
    "reasonCode": "ON_CALL_ROTATION",
    "reviewable": true,
    "record": {
      "recordId": "ROTA-9438",
      "createdBy": "subject_5709",
      "createdAt": "2026-09-12T05:58:00Z",
      "scope": "billing-web"
    }
  },
  {
    "id": "sup-013",
    "ts": "2026-09-14T04:43:52Z",
    "subjectPseudonym": "#3338",
    "anomaly": "New device fingerprint",
    "suppressedBy": "PagerDuty",
    "reasonCode": "ON_CALL_ROTATION",
    "reviewable": true,
    "record": {
      "recordId": "ROTA-7392",
      "createdBy": "subject_9415",
      "createdAt": "2026-09-13T03:42:00Z",
      "scope": "billing-web"
    }
  },
  {
    "id": "sup-001",
    "ts": "2026-09-14T04:19:13Z",
    "subjectPseudonym": "#1852",
    "anomaly": "External share created",
    "suppressedBy": "Okta",
    "reasonCode": "NEW_DEVICE_APPROVED",
    "reviewable": true,
    "record": {
      "recordId": "HR-3972",
      "createdBy": "subject_4128",
      "createdAt": "2026-09-13T00:31:00Z",
      "scope": "payments-core"
    }
  },
  {
    "id": "sup-025",
    "ts": "2026-09-14T03:21:20Z",
    "subjectPseudonym": "#6072",
    "anomaly": "Composition drift, JSD 0.21",
    "suppressedBy": "Jira",
    "reasonCode": "SCOPE_MATCHED_TICKET",
    "reviewable": true,
    "record": {
      "recordId": "TICKET-5509",
      "createdBy": "subject_7197",
      "createdAt": "2026-09-12T05:54:00Z",
      "scope": "billing-web"
    }
  },
  {
    "id": "sup-004",
    "ts": "2026-09-14T02:41:20Z",
    "subjectPseudonym": "#5145",
    "anomaly": "Off-hours authentication",
    "suppressedBy": "Okta",
    "reasonCode": "NEW_DEVICE_APPROVED",
    "reviewable": true,
    "record": {
      "recordId": "HR-4189",
      "createdBy": "subject_1924",
      "createdAt": "2026-09-12T00:42:00Z",
      "scope": "billing-web"
    }
  },
  {
    "id": "sup-020",
    "ts": "2026-09-14T02:31:33Z",
    "subjectPseudonym": "#4002",
    "anomaly": "Off-hours authentication",
    "suppressedBy": "PagerDuty",
    "reasonCode": "ON_CALL_ROTATION",
    "reviewable": true,
    "record": {
      "recordId": "ROTA-7226",
      "createdBy": "subject_5046",
      "createdAt": "2026-09-14T05:52:00Z",
      "scope": "support-tooling"
    }
  },
  {
    "id": "sup-017",
    "ts": "2026-09-14T00:49:59Z",
    "subjectPseudonym": "#5507",
    "anomaly": "Bulk permission read",
    "suppressedBy": "Jira",
    "reasonCode": "SCOPE_MATCHED_TICKET",
    "reviewable": true,
    "record": {
      "recordId": "TICKET-3909",
      "createdBy": "subject_8504",
      "createdAt": "2026-09-12T05:15:00Z",
      "scope": "analytics-dbt"
    }
  },
  {
    "id": "sup-006",
    "ts": "2026-09-14T00:39:06Z",
    "subjectPseudonym": "#8445",
    "anomaly": "Archive creation, 62 files",
    "suppressedBy": "PagerDuty",
    "reasonCode": "ON_CALL_ROTATION",
    "reviewable": true,
    "record": {
      "recordId": "ROTA-9823",
      "createdBy": "subject_1964",
      "createdAt": "2026-09-14T00:55:00Z",
      "scope": "billing-web"
    }
  }
];

export const SUPPRESSION_REASON_LABELS: Record<string, string> = {
  "SCOPE_MATCHED_TICKET": "Scope-matched ticket",
  "ON_CALL_ROTATION": "On-call rotation",
  "APPROVED_TRAVEL": "Approved travel",
  "ROLE_CHANGE": "Role change",
  "NEW_DEVICE_APPROVED": "New device enrolment"
};
